/*
  PCI-E Codes
  Copyright (c) 2023, John Ryland
  All rights reserved.
*/

#pragma once

#include "tree.h"

using pcie_desc_tree_t = tree_t<const char*,250>;

template <> uint16_t pcie_desc_tree_t::last_node_idx = 0;
template <> pcie_desc_tree_t pcie_desc_tree_t::nodes[250] = {};      // TODO : currently need to manually ensure this is big enough

// Reference:
//    Strings comes from the class codes table here: https://wiki.osdev.org/PCI
//    Which are pretty similar to the ones here: https://admin.pci-ids.ucw.cz/read/PD/
static const pcie_desc_tree_t pcie_desc_tree
=
{ 0x00, "PCI Descriptor Tree",
     { { 0x00 , "Unclassified",
            { { 0x00, "Non-VGA-Compatible Unclassified Device"                   } ,
              { 0x01, "VGA-Compatible Unclassified Device"                       } } } ,
       { 0x01 , "Mass Storage Controller"                                        , 
            { { 0x00 , "SCSI Bus Controller"                                     } ,
              { 0x01 , "IDE Controller"                                          ,
                   { { 0x00 , "ISA Compatibility mode-only controller"           } ,
                     { 0x05 , "PCI native mode-only controller"                  } ,
                     { 0x0A , "ISA Compatibility mode controller, supports both channels switched to PCI native mode"                         } ,
                     { 0x0F , "PCI native mode controller, supports both channels switched to ISA compatibility mode"                         } ,
                     { 0x80 , "ISA Compatibility mode-only controller, supports bus mastering"                                                } ,
                     { 0x85 , "PCI native mode-only controller, supports bus mastering"                                                       } ,
                     { 0x8A , "ISA Compatibility mode controller, supports both channels switched to PCI native mode, supports bus mastering" } ,
                     { 0x8F , "PCI native mode controller, supports both channels switched to ISA compatibility mode, supports bus mastering" } } },
              { 0x02 , "Floppy Disk Controller"                                  } ,
              { 0x03 , "IPI Bus Controller"                                      } ,
              { 0x04 , "RAID Controller"                                         } ,
              { 0x05 , "ATA Controller"                                          ,
                   { { 0x20 , "Single DMA"                                       } ,
                     { 0x30 , "Chained DMA"                                      } } } ,
              { 0x06 , "Serial ATA Controller"                                   ,
                   { { 0x00 , "Vendor Specific Interface"                        } ,
                     { 0x01 , "AHCI 1.0"                                         } ,
                     { 0x02 , "Serial Storage Bus"                               } } } ,
              { 0x07 , "Serial Attached SCSI Controller"                         ,
                   { { 0x00 , "SAS"                                              } ,
                     { 0x01 , "Serial Storage Bus"                               } } } ,
              { 0x08 , "Non-Volatile Memory Controller"                          ,
                   { { 0x01 , "NVMHCI"                                           } ,
                     { 0x02 , "NVM Express"                                      } } } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x02 , "Network Controller"                                             ,
            { { 0x00 , "Ethernet Controller"                                     } ,
              { 0x01 , "Token Ring Controller"                                   } ,
              { 0x02 , "FDDI Controller"                                         } ,
              { 0x03 , "ATM Controller"                                          } ,
              { 0x04 , "ISDN Controller"                                         } ,
              { 0x05 , "WorldFip Controller"                                     } ,
              { 0x06 , "PICMG 2.14 Multi Computing Controller"                   } ,
              { 0x07 , "Infiniband Controller"                                   } ,
              { 0x08 , "Fabric Controller"                                       } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x03 , "Display Controller"                                             ,
            { { 0x00 , "VGA Compatible Controller"                               ,
                   { { 0x00 , "VGA Controller"                                   } ,
                     { 0x01 , "8514-Compatible Controller"                       } } } ,
              { 0x01 , "XGA Controller"                                          } ,
              { 0x02 , "3D Controller (Not VGA-Compatible)"                      } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x04 , "Multimedia Controller"                                          ,
            { { 0x00 , "Multimedia Video Controller"                             } ,
              { 0x01 , "Multimedia Audio Controller"                             } ,
              { 0x02 , "Computer Telephony Device"                               } ,
              { 0x03 , "Audio Device"                                            } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x05 , "Memory Controller"                                              , 
            { { 0x00 , "RAM Controller"                                          } ,
              { 0x01 , "Flash Controller"                                        } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x06 , "Bridge"                                                         ,
            { { 0x00 , "Host Bridge"                                             } ,
              { 0x01 , "ISA Bridge"                                              } ,
              { 0x02 , "EISA Bridge"                                             } ,
              { 0x03 , "MCA Bridge"                                              } ,
              { 0x04 , "PCI-to-PCI Bridge"                                       , 
                   { { 0x00 , "Normal Decode"                                    } ,
                     { 0x01 , "Subtractive Decode"                               } } } ,
              { 0x05 , "PCMCIA Bridge"                                           } ,
              { 0x06 , "NuBus Bridge"                                            } ,
              { 0x07 , "CardBus Bridge"                                          } ,
              { 0x08 , "RACEway Bridge"                                          , 
                   { { 0x00 , "Transparent Mode"                                 } ,
                     { 0x01 , "Endpoint Mode"                                    } } } ,
              { 0x09 , "PCI-to-PCI Bridge"                                       , 
                   { { 0x40 , "Semi-Transparent, Primary bus towards host CPU"   } ,
                     { 0x80 , "Semi-Transparent, Secondary bus towards host CPU" } } },
              { 0x0A , "InfiniBand-to-PCI Host Bridge"                           } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x07 , "Simple Communication Controller"                                ,
            { { 0x00 , "Serial Controller"                                       ,
                   { { 0x00 , "8250-Compatible (Generic XT)"                     } ,
                     { 0x01 , "16450-Compatible"                                 } ,
                     { 0x02 , "16550-Compatible"                                 } ,
                     { 0x03 , "16650-Compatible"                                 } ,
                     { 0x04 , "16750-Compatible"                                 } ,
                     { 0x05 , "16850-Compatible"                                 } ,
                     { 0x06 , "16950-Compatible"                                 } } },
              { 0x01 , "Parallel Controller"                                     ,
                   { { 0x00 , "Standard Parallel Port"                           } ,
                     { 0x01 , "Bi-Directional Parallel Port"                     } ,
                     { 0x02 , "ECP 1.X Compliant Parallel Port"                  } ,
                     { 0x03 , "IEEE 1284 Controller"                             } ,
                     { 0xFE , "IEEE 1284 Target Device"                          } } },
              { 0x02 , "Multiport Serial Controller"                             } ,
              { 0x03 , "Modem"                                                   ,
                   { { 0x00 , "Generic Modem"                                    } ,
                     { 0x01 , "Hayes 16450-Compatible Interface"                 } ,
                     { 0x02 , "Hayes 16550-Compatible Interface"                 } ,
                     { 0x03 , "Hayes 16650-Compatible Interface"                 } ,
                     { 0x04 , "Hayes 16750-Compatible Interface"                 } } },
              { 0x04 , "IEEE 488.1/2 (GPIB) Controller"                          } ,
              { 0x05 , "Smart Card Controller"                                   } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x08 , "Base System Peripheral"                                         , 
            { { 0x00 , "PIC"                                                     ,
                   { { 0x00 , "Generic 8259-Compatible"                          } ,
                     { 0x01 , "ISA-Compatible"                                   } ,
                     { 0x02 , "EISA-Compatible"                                  } ,
                     { 0x10 , "I/O APIC Interrupt Controller"                    } ,
                     { 0x20 , "I/O(x) APIC Interrupt Controller"                 } } } ,
              { 0x01 , "DMA Controller"                                          , 
                   { { 0x00 , "Generic 8237-Compatible"                          } ,
                     { 0x01 , "ISA-Compatible"                                   } ,
                     { 0x02 , "EISA-Compatible"                                  } } } ,
              { 0x02 , "Timer"                                                   ,
                   { { 0x00 , "Generic 8254-Compatible"                          } ,
                     { 0x01 , "ISA-Compatible"                                   } ,
                     { 0x02 , "EISA-Compatible"                                  } ,
                     { 0x03 , "HPET"                                             } } } ,
              { 0x03 , "RTC Controller"                                          , 
                   { { 0x00 , "Generic RTC"                                      } ,
                     { 0x01 , "ISA-Compatible"                                   } } } ,
              { 0x04 , "PCI Hot-Plug Controller"                                 } ,
              { 0x05 , "SD Host controller"                                      } ,
              { 0x06 , "IOMMU"                                                   } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x09 , "Input Device Controller"                                        , 
            { { 0x00 , "Keyboard Controller"                                     } ,
              { 0x01 , "Digitizer Pen"                                           } ,
              { 0x02 , "Mouse Controller"                                        } ,
              { 0x03 , "Scanner Controller"                                      } ,
              { 0x04 , "Gameport Controller"                                     , 
                   { { 0x00 , "Generic"                                          } ,
                     { 0x10 , "Extended"                                         } } } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x0A , "Docking Station"                                                ,
            { { 0x00 , "Generic"                                                 } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x0B , "Processor"                                                      , 
            { { 0x00 , "386"                                                     } ,
              { 0x01 , "486"                                                     } ,
              { 0x02 , "Pentium"                                                 } ,
              { 0x03 , "Pentium Pro"                                             } ,
              { 0x10 , "Alpha"                                                   } ,
              { 0x20 , "PowerPC"                                                 } ,
              { 0x30 , "MIPS"                                                    } ,
              { 0x40 , "Co-Processor"                                            } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x0C , "Serial Bus Controller"                                          , 
            { { 0x00 , "FireWire (IEEE 1394) Controller"                         , 
                   { { 0x00 , "Generic"                                          } ,
                     { 0x10 , "OHCI"                                             } } } ,
              { 0x01 , "ACCESS Bus Controller"                                   } ,
              { 0x02 , "SSA"                                                     } ,
              { 0x03 , "USB Controller"                                          ,
                   { { 0x00 , "UHCI Controller"                                  } ,
                     { 0x10 , "OHCI Controller"                                  } ,
                     { 0x20 , "EHCI (USB2) Controller"                           } ,
                     { 0x30 , "XHCI (USB3) Controller"                           } ,
                     { 0x80 , "Unspecified"                                      } ,
                     { 0xFE , "USB Device (Not a host controller)"               } } } ,
              { 0x04 , "Fibre Channel"                                           } ,
              { 0x05 , "SMBus Controller"                                        } ,
              { 0x06 , "InfiniBand Controller"                                   } ,
              { 0x07 , "IPMI Interface"                                          , 
                   { { 0x00 , "SMIC"                                             } ,
                     { 0x01 , "Keyboard Controller Style"                        } ,
                     { 0x02 , "Block Transfer"                                   } } } ,
              { 0x08 , "SERCOS Interface (IEC 61491)"                            } ,
              { 0x09 , "CANbus Controller"                                       } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x0D , "Wireless Controller"                                            , 
            { { 0x00 , "iRDA Compatible Controller"                              } ,
              { 0x01 , "Consumer IR Controller"                                  } ,
              { 0x10 , "RF Controller"                                           } ,
              { 0x11 , "Bluetooth Controller"                                    } ,
              { 0x12 , "Broadband Controller"                                    } ,
              { 0x20 , "Ethernet Controller (802.1a)"                            } ,
              { 0x21 , "Ethernet Controller (802.1b)"                            } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x0E , "Intelligent Controller"                                         ,
            { { 0x00 , "I20"                                                     } } } ,
       { 0x0F , "Satellite Communication Controller"                             ,
            { { 0x01 , "Satellite TV Controller"                                 } ,
              { 0x02 , "Satellite Audio Controller"                              } ,
              { 0x03 , "Satellite Voice Controller"                              } ,
              { 0x04 , "Satellite Data Controller"                               } } } ,
       { 0x10 , "Encryption Controller"                                          ,
            { { 0x00 , "Network and Computing Encrpytion/Decryption"             } ,
              { 0x10 , "Entertainment Encryption/Decryption"                     } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x11 , "Signal Processing Controller"                                   ,
            { { 0x00 , "DPIO Modules"                                            } ,
              { 0x01 , "Performance Counters"                                    } ,
              { 0x10 , "Communication Synchronizer"                              } ,
              { 0x20 , "Signal Processing Management"                            } ,
              { 0x80 , "Other"                                                   } } } ,
       { 0x12 , "Processing Accelerator"                                         } ,
       { 0x13 , "Non-Essential Instrumentation"                                  } ,
       { 0x14 , "0x3F (Reserved)"                                                } ,
       { 0x40 , "Co-Processor"                                                   } ,
       { 0x41 , "0xFE (Reserved)"                                                } ,
       { 0xFF , "Unassigned Class (Vendor specific)"                             } } }
;
