#
# Bootstrap Makefile for building bootloader
# (C) Copyright 2023
# John Ryland
#

all: release

# -include ../../tools/build/Generic.mak

-include ../../tools/build/build_start.inc

-include $(PROJECT_FILE)

-include ../../tools/build/build_end.inc
